### ISSUE TITLE
Multi instance in one page

### ISSUE THREAD

**Issue by sama55** [webcreate/infinite-ajax-scroll#93]
Thank you great plugin. There are multiple page-navigation on "one" page in my site. It works almost well. However, I have one problem. Trigger tag (.ias_trigger ["Load more items"]) of B instance disappears by $(window) scroll of A.

"scrollContainer" of A instance: $(window)
"scrollContainer" of B instance: $('Unique ID')

It seems that trigger tag of IAS has CLASS (.ias_trigger) not ID.

Question1: Is the multiple instance impossible in one page?
Question2: Can I deal by onScroll() callback?

Best regards.

**Comment by fieg** [comment]
> In theory the unbind/destroy method should clean up all traces of IAS so as if it were never initialized.

@longzheng this should now be fixed in v2.2.0. Can you verify this?

**Comment by jackhad** [comment]
I think its not fixed.I have tried in http://www.yiiframework.com/extension/yiinfinite-scroll/ with new version of JS

**Comment by fieg** [comment]
Yiinfinite-scroll is seems totally not related to Infinite AJAX Scroll.

**Comment by mikerogne** [comment]
I am also experiencing this issue with v2.2.0.

**Comment by hitesh2088** [comment]
Finally reading all the comments I am also one who face the same issue for multiple tab with use of ifiniteajaxscroll in each tab ...any good news

**Comment by ses2013** [comment]
Any hope on this or Info how to do that?
Cheers + Thanks
Stefan

**Comment by hitesh2088** [comment]
You can use the Link pager widget  with listview and add below jquery which will just replace ur next button to ur HTML;
```javascript

 $("#pagination3 > .prev ").css("display","none");

$("#pagination3 > .next3 > a").click(function(e){
     e.preventDefault();
     
     $.ajax({
         url: $(this).attr("href"),
         type: "get",
         success: function(data) {
               var items =$(data).find("#list-wrapper3 > .item3") ;
               $("#list-wrapper3 ").append(items);
             
               if($(data).find("#pagination3 > li.next3").hasClass("disabled")){
                 $("#pagination3 > .next3 > a").remove();
                 $("#pagination3 > .next3  ").text("No more items to display");
               }
              else { 
               var next3 = $(data).find("#pagination > li.next3 > a").attr("href") ;              
             $("#pagination3 > .next3 > a").attr("href",next3);
             }

         }
     }); 


 })
 ```
and Linkpager will be below code
```php
LinkPager::widget([
         'pagination' => $pages3,

         'nextPageLabel' => 'Load more',
         'nextPageCssClass'=>'load-more text-center next3',
         'options'=>['tag'=>'div','class'=>'load-more','id'=>'pagination3' ],
         'maxButtonCount'=> 0,
               ]);  
```

**Comment by ses2013** [comment]
Thanks for your Idea.
And the I duplicate the code for #pagination1 and #pagination2 ?
Thanks for some more input ...
Cheers
Stefan

**Comment by ses2013** [comment]
dear hitesh2088,
could you be so kind to point me to an solution here?
do you have any working url or some https://jsfiddle.net set up?
that would be very kind.
thanks again for your kindly help.
stefan

**Comment by hitesh2088** [comment]
Dear,
The simple logic is Linkpager will generate pagination in which 'maxButtonCount'=> 0, which gives only prev and next button out of which prev is not required so display none and next button u can have css applied as you required and the click of that button should fetch data with ajax and append that in the same container of list view widget ...

I hope you understand I have implemented this in one of the client project dont have any jsfiddle

**Comment by ses2013** [comment]
Hey, is it possible you are talking about a complete different Extension?
yii2-scroll-pager
'cause I can't find the explanation for a "LinkPager::widget" in here.
Best

**Comment by hitesh2088** [comment]
Link pager is widget of Yii2 by which pagination can be created 
[check this out ](http://www.yiiframework.com/doc-2.0/yii-widgets-linkpager.html )

**Comment by kop** [comment]
@fieg do you have any time for this? Maybe you need some help with test data or something else (I wanted to create a PR, but I can't find an issue)?

This issue is really frustrating...

**Comment by sjorsrijsdam** [comment]
With my PR merged in master multiple instances should be reliably possible now. One thing to note is that you should not nest scroll containers when you do. The outer scroll container might start working with elements from the inner scroll container.

**Comment by aerionTech** [comment]
HI, I am still experiencing an issue with two instances setup on the same page. We are using 2.2.2

When using the dev tools and inspecting the more button, it initially it has the class "ias-trigger-idea" once click it get replaced and "ias-trigger-challenges" is in it's place, then clicking for the second time performs the paging and the button that is displayed is "ias-trigger-idea".

It seems that the registering of extensions is incorrect when multiple instances are setup. If I comment out the trigger extension on the second instance the paging works correctly

```javascript
$(function () {
    var iasIdea = jQuery.ias({
        container: '#ideasList',
        item: '.krown-id-item',
        pagination: '.ideas .pagination',
        next: '.ideas .pagination .next'
    });
    // Add a loader image which is displayed during loading
    iasIdea.extension(new IASSpinnerExtension({
        html: '<div class="ias-spinner-idea" style="text-align: center;"><img src="{src}"/></div>'
    }));
    iasIdea.extension(new IASTriggerExtension({
        offset: 1,
        html: '<div class="ias-trigger-idea ias-trigger-next-idea"><a>{text}</a></div>'
    }));
    iasIdea.extension(new IASPagingExtension());


    var iasChallenge = jQuery.ias({
        container: '#campaignsList',
        item: '.article',
        pagination: '.challenges .pagination',
        next: '.challenges .pagination .next'
    });

    iasChallenge.extension(new IASSpinnerExtension({
        html: '<div class="ias-spinner-challenge" style="text-align: center;"><img src="{src}"/></div>'
   }));

    iasChallenge.extension(new IASTriggerExtension({
        offset: 1,
        html: '<div class="ias-trigger-challenge ias-trigger-next-challenge"><a>{text}</a></div>'
    }));

    iasChallenge.extension(new IASPagingExtension()); 
});
```
